if(WIN32)
    set(FASTCG_PLATFORM "Windows")
elseif(UNIX AND NOT APPLE)
    set(FASTCG_PLATFORM "Linux")
endif()

if (CMAKE_BUILD_TYPE STREQUAL "Debug" AND FASTCG_PLATFORM STREQUAL "Linux")
	add_definitions(-D_DEBUG=1)
endif()

set(FASTCG_RENDERING_SYSTEM "OpenGL")

set(FASTCG_DEPLOY ${CMAKE_SOURCE_DIR}/deploy)

set_property(DIRECTORY PROPERTY ADDITIONAL_MAKE_CLEAN_FILES ${FASTCG_DEPLOY})