set(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_C_COMPILER cl CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER cl CACHE FILEPATH "" FORCE)
set(CMAKE_RC_COMPILER rc CACHE FILEPATH "" FORCE)

set(CMAKE_C_STANDARD 17)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# allow runtime selection via CMAKE_MSVC_RUNTIME_LIBRARY
# (needs CMP0091 NEW so the variable actually takes effect)
if(POLICY CMP0091)
  cmake_policy(SET CMP0091 NEW)
endif()

# default to static runtime in release, static-debug in debug (customize as desired)
# options: MultiThreaded, MultiThreadedDLL, MultiThreadedDebug, MultiThreadedDebugDLL
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>" CACHE STRING "")

set(CMAKE_C_FLAGS_DEBUG_INIT "/Od /Zi")
set(CMAKE_C_FLAGS_RELWITHDEBINFO_INIT "/O2 /Zi /DNDEBUG")
set(CMAKE_C_FLAGS_RELEASE_INIT "/O2 /DNDEBUG")

set(CMAKE_CXX_FLAGS_DEBUG_INIT "/Od /Zi")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "/O2 /Zi /DNDEBUG")
set(CMAKE_CXX_FLAGS_RELEASE_INIT "/O2 /DNDEBUG")

set(ENABLE_LTO OFF CACHE BOOL "Enable LTCG (/GL + /LTCG)")
if(ENABLE_LTO)
  set(CMAKE_C_FLAGS_RELEASE_INIT "${CMAKE_C_FLAGS_RELEASE_INIT} /GL")
  set(CMAKE_CXX_FLAGS_RELEASE_INIT "${CMAKE_CXX_FLAGS_RELEASE_INIT} /GL")
  set(CMAKE_C_FLAGS_RELWITHDEBINFO_INIT "${CMAKE_C_FLAGS_RELWITHDEBINFO_INIT} /GL")
  set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "${CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT} /GL")

  set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS_RELEASE} /LTCG")
  set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "${CMAKE_SHARED_LINKER_FLAGS_RELEASE} /LTCG")
  set(CMAKE_STATIC_LINKER_FLAGS_RELEASE "${CMAKE_STATIC_LINKER_FLAGS_RELEASE} /LTCG")
  set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO} /LTCG")
  set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO "${CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO} /LTCG")
  set(CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO "${CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO} /LTCG")
endif()

set(CMAKE_FIND_PACKAGE_PREFER_CONFIG ON)
set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS OFF CACHE BOOL "Export all symbols by default for SHARED libs")
