name: Format C++ Code

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
          ref: ${{ github.head_ref }}

    - name: Install clang-format
      run: | 
        sudo apt-get install -y clang-format-15
        sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-15 100
        sudo update-alternatives --set clang-format /usr/bin/clang-format-15

    - name: Run clang-format
      run: |
        chmod +x ./format_sources.sh
        ./format_sources.sh

    - name: Check for code format changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        if ! git diff --cached --exit-code; then
          git commit -m "Applied format changes."
          git push origin HEAD:${{ github.head_ref }}
          echo "Applied format changes."
        else
          echo "No formatting changes required."
        fi
